pipeline {
    agent {
        label 'docker-agent'
    }
    
    stages {
/*        stage('Checkout code and prepare environment') {
            steps {
                git url: 'https://github.com/ryanblair111/UML_DevOps.git', 
                branch: 'main'
                        sh """
                            cd Chapter08/sample1
                            chmod +x gradlew
                        """
            }
        }*/

        stage ('Run CodeCoverage test plus others if main branch') {
            when { 
                anyOf {
                    branch 'main'
                    expression { env.CHANGE_BRANCH == 'main'}
                    }
            }
            steps {
                sh """
                cd Chapter08/sample1
                chmod +x gradlew
                ./gradlew jacocoTestCoverageVerification
                ./gradlew test
                ./gradlew jacocoTestReport
                ./gradlew checkstyleMain
                """
                publishHTML (
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/tests/test',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
                    ]
                )
                publishHTML (
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: "JaCoCo Checkstyle"
                        ]
                )
            }
        }

        stage ('Run tests other than CodeCoverage on other branches') {
            when { 
                not {
                    anyOf { 
                        branch 'main'
                        expression { env.CHANGE_BRANCH == 'main'}
                    }
                }
            }
            steps {
                sh """
                cd Chapter08/sample1
                chmod +x gradlew
                ./gradlew test
                ./gradlew jacocoTestReport
                ./gradlew checkstyleMain
                """
                publishHTML (
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/tests/test',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
                    ]
                )
                publishHTML (
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: "JaCoCo Checkstyle"
                        ]
                )
                //set build to receive an error
                error("Build failed because it is not a main or feature branch")
            }
        }
        
    }
    post {
	    failure {
	        echo 'Tests fail!'
	    }
	    success {
		    echo 'Tests pass!'
	    }
    }
}
