agent { label 'docker-agent' }

stages {
	stage('prepare environment') {
		when { branch 'main' }
		steps {
			echo 'all branches'
		}
	}
	
	stage('unit test') {
		when {
			not { branch 'main' }
		}
		steps {
			echo 'Unit test not main branch'
		}

	}
	
	stage('cat README') {
		when {
			branch 'fix*'
		}
		steps {
			sh '''
			  cat README.md
			'''
		}
	}
}
